---
name: 'AWS Serverless Action'
description: 'A GitHub Action for deploying with Serverless Framework'
author: 'Anthony Yung <antyung41@gmail.com>'
branding:
  icon: 'zap'
  color: 'blue'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  aws_region:
    description: 'AWS Region'
    default: 'ap-south-1'
    required: true
  serverless_file:
    description: 'Serverless configuration file'
    default: 'serverless.yml'
    required: true

runs:
  using: 'docker'
  image: 'docker://ghcr.io/sudo88com/aws-serverless-action:latest'
  entrypoint: /bin/bash
  args:
    - -c
    - |
        set -o errexit -o pipefail
        export AWS_ACCESS_KEY_ID="${{ inputs.aws_access_key_id }}"
        export AWS_SECRET_ACCESS_KEY="${{ inputs.aws_secret_access_key }}"
        export AWS_DEFAULT_REGION="${{ inputs.aws_region }}"
        export SERVERLESS_FILE="${{ inputs.serverless_file }}"
        echo AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        echo AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        echo AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION
        echo SERVERLESS_FILE=$SERVERLESS_FILE
        curl -fsSL https://raw.githubusercontent.com/sudo88com/aws-serverless-action/main/action.sh | bash -s -- main
