---
name: Docker Build- serverless

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_SECRET }}

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          NODE_VERSION=$(grep -oP '^ARG NODE_VERSION=\K.*' Dockerfile)
          echo "NODE_VERSION=${NODE_VERSION}" >> $GITHUB_ENV
          echo "NODE_VERSION=${NODE_VERSION}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/serverless:${NODE_VERSION}
            ghcr.io/${{ github.repository }}/serverless:latest

      - name: Run Slack Notification
        if: always()
        uses: sudo88com/slacknotify-action@v1
        with:
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
